### ISSUE TITLE
Issue with i3-gaps-9999

### ISSUE THREAD

**Issue by ghost** [0x4d4c/gentoo-overlay#1]
I have encountered an error with the ebuild.

/var/tmp/portage/x11-wm/i3-gaps-9999/temp/environment: line 2617: epatch_user: command not found

http://pastebin.com/ULf0PAzf

**Comment by 0x4d4c** [comment]
Thanks for reporting! The live ebuilds should be working again now. If there are still issue feel free to re-open this issue or open a new one.
